# Generated by Django 4.1 on 2022-08-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_resume_delete_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='age',
        ),
    ]
