# Generated by Django 4.1 on 2022-08-25 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_resume_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='qualification',
            field=models.CharField(choices=[('BS', 'BS'), ('MS', 'MS')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
