# Generated by Django 4.1 on 2022-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_resume_qualification_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_sector',
            field=models.IntegerField(choices=[(1, 'Accountancy, Banking and Finance'), (2, 'Engineering and Manufacturing'), (3, 'Agriculture'), (4, 'Health'), (5, 'Property and Construction'), (6, 'Education')], default=1),
        ),
    ]
