# Generated by Django 4.1 on 2023-02-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_jobposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
