# Generated by Django 4.1 on 2023-02-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_resume_selected_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='is_selected',
        ),
    ]
