# Generated by Django 4.1 on 2023-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_resume_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
