# Generated by Django 4.1 on 2023-02-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_resume_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='selected_for_job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_for_job', to='main_app.jobposted'),
        ),
    ]
