# Generated by Django 4.1 on 2023-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_resume_selected_for_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='selection_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
